function PlayTeaser(player)
    CinematicModeBJ(true, GetForceOfPlayer(player))
    CinematicFadeBJ( bj_CINEFADETYPE_FADEOUT, 2, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    PolledWait(2.0)
    CameraSetupApplyForPlayer(false, udg_Camera_Teaser[1], player, 0.0)
    SetCameraField(CAMERA_FIELD_FARZ, 99999, 0)
    SetTerrainFogExBJ( 0, 99999.00, 99999.00, 0, 100, 100, 100 )
    FogMaskEnable(false)
    BlzShowSkyBox( true )
    BlzShowTerrain( true )
    FogEnableOff(  )
    CreateFogModifierRectBJ( true, player, FOG_OF_WAR_VISIBLE, GetEntireMapRect())
    CinematicFadeBJ( bj_CINEFADETYPE_FADEIN, 2, "ReplaceableTextures\\CameraMasks\\White_mask.blp", 0, 0, 0, 0 )
    PolledWait(2.0)
    CameraSetupApplyForPlayer(true, udg_Camera_Teaser[2], player, 5.0)
    PolledWait(5.0)
    GameNotice("Thanks for trying out the demo! - Salepate", player)
    PolledWait(2.0)
    CameraSetupApplyForPlayer(true, udg_Camera_Teaser[3], player, 3.0)
    PolledWait(3.0)
    CustomVictoryBJ(player, true, true)
end